apiVersion: v1
kind: Service
metadata:
  name: fabric-mc-svc
  labels:
    app: fabric-mc

spec:
  ports:
    - protocol: TCP
      name: minecraft
      port: 25565
    - protocol: TCP
      name: rcon
      port: 25575
  selector:
    app: fabric-mc
