apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: fabric-mc
  labels:
    app: fabric-mc

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabric-mc
  template:
    metadata:
      labels:
        app: fabric-mc
    spec:
      nodeName: worker-1
      containers:
        - name: fabric-mc
          image: ghcr.io/dylanbulmer/minecraft-fabric:latest
          env:
            - name: MINECRAFT_VERSION
              value: '1.17'
            - name: MINECRAFT_PORT
              value: '25565'
            - name: MINECRAFT_EULA
              value: 'true'
            - name: MINECRAFT_MAXHEAP
              value: '4096M'
          volumeMounts:
            - name: data
              mountPath: /server
          ports:
            - name: minecraft
              containerPort: 25565
            - name: rcon
              containerPort: 25575
      volumes:
        - name: data
          hostPath:
            path: /var/mc/fabric/server
