apiVersion: v1
kind: Service
metadata:
  name: fabric-mc
  labels:
    app: minecraft-fabric

spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: minecraft
      port: 25565
      targetPort: 25565
    - protocol: TCP
      name: rcon
      port: 25575
      targetPort: 25575
  externalIPs:
    - 192.168.1.100
  selector:
    app: minecraft-fabric
